#!/usr/bin/env bash
# Install git hooks for claude-playbook
# Usage: ./install-hooks.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

if [[ ! -d "$REPO_ROOT/.git" ]]; then
    echo "ERROR: Not a git repository: $REPO_ROOT"
    exit 1
fi

mkdir -p "$HOOKS_DIR"

# --- pre-commit hook ---
PRE_COMMIT="$HOOKS_DIR/pre-commit"

cat > "$PRE_COMMIT" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh — do not edit directly
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# 1. Check for shell injection in AI command files
"$REPO_ROOT/scripts/hooks/check-command-injection.sh"

# 2. Check YAML frontmatter (if implemented)
if [[ -x "$REPO_ROOT/scripts/hooks/check-yaml-frontmatter.sh" ]]; then
    "$REPO_ROOT/scripts/hooks/check-yaml-frontmatter.sh"
fi

# 3. Check commit message format (if implemented)
# Note: commit-msg hook is separate, not pre-commit
HOOK

chmod +x "$PRE_COMMIT"
echo "[installed] pre-commit -> check-command-injection"

# --- commit-msg hook ---
COMMIT_MSG="$HOOKS_DIR/commit-msg"

cat > "$COMMIT_MSG" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ -x "$REPO_ROOT/scripts/hooks/check-commit-msg.sh" ]]; then
    "$REPO_ROOT/scripts/hooks/check-commit-msg.sh" "$1"
fi
HOOK

chmod +x "$COMMIT_MSG"
echo "[installed] commit-msg"

echo ""
echo "Git hooks installed in $HOOKS_DIR"
