#!/usr/bin/env bash
# Install git hooks for claude-playbook.
# If pre-commit framework is available and .pre-commit-config.yaml exists,
# uses 'pre-commit install'. Otherwise falls back to manual hook generation.
#
# Works both as a standalone repo and as a submodule.
# Usage: ./install-hooks.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Resolve hooks directory — handles both standalone repos (.git is a dir)
# and submodules (.git is a file pointing to ../.git/modules/<name>)
if [[ -d "$REPO_ROOT/.git" ]]; then
    GIT_DIR="$REPO_ROOT/.git"
elif [[ -f "$REPO_ROOT/.git" ]]; then
    # Submodule: .git file contains "gitdir: <path>"
    GIT_DIR="$(sed 's/^gitdir: //' "$REPO_ROOT/.git")"
    if [[ "$GIT_DIR" != /* ]]; then
        GIT_DIR="$REPO_ROOT/$GIT_DIR"
    fi
    GIT_DIR="$(cd "$GIT_DIR" && pwd)"
else
    echo "ERROR: Not a git repository: $REPO_ROOT"
    exit 1
fi

HOOKS_DIR="$GIT_DIR/hooks"

# ---------------------------------------------------------------------------
# Strategy 1: Use pre-commit framework if available
# ---------------------------------------------------------------------------
if [[ -f "$REPO_ROOT/.pre-commit-config.yaml" ]] && command -v pre-commit &>/dev/null; then
    echo "Using pre-commit framework..."
    cd "$REPO_ROOT"
    pre-commit install --install-hooks
    pre-commit install --hook-type commit-msg
    echo ""
    echo "Git hooks installed via pre-commit in $HOOKS_DIR"
    exit 0
fi

# ---------------------------------------------------------------------------
# Strategy 2: Manual hook generation (fallback)
# ---------------------------------------------------------------------------
if [[ -f "$REPO_ROOT/.pre-commit-config.yaml" ]]; then
    echo "NOTE: .pre-commit-config.yaml found but 'pre-commit' not installed."
    echo "      Install with: pip install pre-commit"
    echo "      Falling back to manual hook installation."
    echo ""
fi

mkdir -p "$HOOKS_DIR"

# --- pre-commit hook ---
PRE_COMMIT="$HOOKS_DIR/pre-commit"

cat > "$PRE_COMMIT" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh — do not edit directly
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# 1. Check for shell injection in AI command files
"$REPO_ROOT/scripts/hooks/check-command-injection.sh"

# 2. Check YAML frontmatter (if implemented)
if [[ -x "$REPO_ROOT/scripts/hooks/check-yaml-frontmatter.sh" ]]; then
    "$REPO_ROOT/scripts/hooks/check-yaml-frontmatter.sh"
fi

# 3. Check commit message format (if implemented)
# Note: commit-msg hook is separate, not pre-commit
HOOK

chmod +x "$PRE_COMMIT"
echo "[installed] pre-commit -> check-command-injection"

# --- commit-msg hook ---
COMMIT_MSG="$HOOKS_DIR/commit-msg"

cat > "$COMMIT_MSG" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ -x "$REPO_ROOT/scripts/hooks/check-commit-msg.sh" ]]; then
    "$REPO_ROOT/scripts/hooks/check-commit-msg.sh" "$1"
fi
HOOK

chmod +x "$COMMIT_MSG"
echo "[installed] commit-msg"

echo ""
echo "Git hooks installed in $HOOKS_DIR"
